### PR TITLE
Add Wireframe Lo-Fi

### LINKED ISSUE #2: [0.0.1-alpha] Missing Wireframe Lo-Fi
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

### PR DESCRIPTION
**Pull request by samanthabaita**
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

## Issue

Closes #2 

## Benefits

The wireframes Lo-Fi allows developers to understand the layout of Alianco.

## Context

With these wireframes Lo-Fi developers can understand the layout and starting to develop Alianco accordingly.

### CODE REVIEW

**Comment by lucyskyy** [comment]
I can't understand the order of the screens

**Comment by samanthabaita** [comment]
@lucyskyy would you like to have a sigle SVG where there are all the wireframes and a sequence of the various screens?

**Comment by davidegiovanni** [comment]
Speaking of the «Crea nuova organizzazione» button, I'd use a plus icon under the list of orgs and not a specific button at the end of the side bar. What do you think?

**Comment by samanthabaita** [comment]
@davidegiovanni it is a good idea, I thought to put it at the end of the colon but I can change it

**Comment by lucyskyy** [comment]
@samanthabaita Thinking about there's no need since there's a already a user path in the specs

**Comment by samanthabaita** [comment]
@davidegiovanni what do you think of the changes?

**Comment by davidegiovanni** [comment]
Ok, I think it is better - the call-to-action it represents it's secondary so it shul not be that visible.

**Comment by hashbardd** [comment]
Hi @samanthabaita 

I can't understand in `create-realm-form.svg` how the logo upload should work and where to put inputs labels 😄

**Comment by hashbardd** [comment]
@samanthabaita What do you think about placeholders in inputs?

**Comment by samanthabaita** [comment]
@hashbardd Great idea! I update the wireframe :blush:

**Pull request merged**
